# Generated by Django 4.1.5 on 2023-01-23 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos_productos',
            fields=[
                ('tipo_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del tipo de producto')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo del tipo de producto')),
                ('tipo_nombre', models.CharField(max_length=100, verbose_name='Tipo de producto')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga del registro')),
                ('fecha_update', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del producto')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo de producto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('precio', models.FloatField(default=0, verbose_name='Precio del producto')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga del registro')),
                ('fecha_update', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('tipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipos_productos', verbose_name='Id de tipo de producto')),
            ],
        ),
    ]
