# Generated by Django 4.1.5 on 2023-01-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id del producto'),
        ),
        migrations.AlterField(
            model_name='tipos_productos',
            name='tipo_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id del tipo de producto'),
        ),
    ]
